name: 'action-docker-tag'
description: 'A action to push multiple tags to a remote repository based on version number'
author: 'Ed FitzGerald'
#inputs: {}
#  milliseconds: # change this
#    required: true
#    description: 'input description here'
#    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
