name: 'action-docker-tag'
description: 'A action to push multiple tags to a remote repository based on version number'
author: 'Ed FitzGerald'
inputs:
  repo:
    required: true
    description: 'the name of the repo for the docker images'
    default: ''
  dockerfile:
    required: false
    description: 'the path to the dockerfile to build'
    default: 'Dockerfile'
  context:
    required: false
    description: 'the path to the context for the build'
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
